# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Twig\GlobalPessoaExtension:
        arguments: ["@doctrine.orm.entity_manager", "@security.helper"]
        tags: ["twig.extension"]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/DataFixtures/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
# ... (conte√∫do existente do arquivo) ...

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Repository\TiposEnderecosRepository: ~
    Symfony\Component\Security\Csrf\CsrfTokenManagerInterface:
        alias: security.csrf.token_manager
        public: true

    App\Service\ConfiguracaoApiBancoService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\SantanderAuthService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\EmailService:
        arguments:
            $emailRemetente: '%env(MAILER_FROM_EMAIL)%'
            $nomeRemetente: '%env(MAILER_FROM_NAME)%'

    App\Service\CobrancaContratoService:
        arguments:
            $projectDir: '%kernel.project_dir%'